### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by k1z** [X3ZvaWQ/gubot#2]
monent 这个包名是不是写错了？ 应该是moment吧

**Comment by x3zvawq** [comment]
啊这 确有此事 Orz

**Comment by k1z** [comment]
有联系方式吗？ 加个联系， 出现了其他的问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "X3ZvaWQ/gubot"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月1日(星期一) 下午4:39
收件人:&nbsp;"X3ZvaWQ/gubot"<gubot@noreply.github.com&gt;;
抄送:&nbsp;"k1z"<1911518271@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [X3ZvaWQ/gubot] 安装失败 (#2)





 
啊这 确有此事 Orz
