### ISSUE TITLE
默认接口是不是挂了？

### ISSUE THREAD

**Issue by ghn9264** [X3ZvaWQ/gubot#4]
https://nico.nicemoe.cn/中的接口都不能用了，是修改了吗？

**Comment by x3zvawq** [comment]
是的 jx3api的域名现在是 jx3api.com 
这些api可以查看这个文档地址：[jx3api-doc](https://jx3api.com/)
可以修改机器人env.json配置文件内的jx3api_baseurl的值为“https://jx3api.com/”来应用新的域名
